import { DataItem } from "./data_item.slint";
import { ScrollView } from "std-widgets.slint";


export component Column inherits Rectangle {
    in property <[string]> items;
    in property <int> selected-index: -1;
    
    width: 250px;
    background: #2b2b2b;
    border-width: 1px;
    border-color: #1a1a1a;
    
    ScrollView {
        VerticalLayout {
            padding: 0px;
            
            for item[idx] in items: DataItem {
                item-name: item;
                is-folder: true;
                is-selected: idx == selected-index;
            }
        }
    }
}
