[package]
name = "slint-demo"
authors = ["Sijun Yang <yangsijun5528@gmail.com>"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.14.0"

[build-dependencies]
slint-build = "1.14.0"
